name: solyric_app
description: Social music applicacion.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  moor_flutter: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^3.0.0
  http: ^0.12.0+2
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.18.0
  extended_text_field: ^0.4.7
  vibrate: ^0.0.4
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_fonts: ^1.1.0
  permission_handler: ^5.0.0+hotfix.3
  audioplayers: ^0.15.1
  record_mp3: ^2.0.0
  intl: ^0.16.1
  build_runner:
  moor_generator: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - guitar_chords.json
    - assets/login_background.png
    - assets/auth_background_gradient.png
    - assets/background_record.png
    - assets/tutorial1.png
    - assets/tutorial2.png
    - assets/tutorial3.png
    - assets/tutorial4.png
    - assets/tutorial5.png
    - assets/tutorial6.png
    - assets/tutorial7.png
    - assets/tutorial8.png
    - assets/solyric_logo.png
    - assets/ic_account.svg
    - assets/ic_bell.svg
    - assets/ic_chords.svg
    - assets/ic_edit.svg
    - assets/ic_explore.svg
    - assets/ic_heart.svg
    - assets/ic_message.svg
    - assets/ic_mic.svg
    - assets/ic_plus.svg
    - assets/ic_search.svg
    - assets/ic_send.svg
    - assets/ic_lines.svg
    - assets/ic_book.svg
    - assets/ic_settings.svg
    - assets/ic_time.svg
    - assets/ic_audio.svg
    - assets/ic_user.svg
    - assets/ic_lock.svg
    - assets/ic_google_plus.svg
    - assets/ic_twitter.svg
    - assets/ic_facebook.svg
    - assets/ic_play.svg
    - assets/ic_next.svg
    - assets/ic_previous.svg
    - assets/ic_guitar.svg
    - assets/ic_piano.svg
    - assets/ic_trash.svg
    - assets/A9-1.png
    - assets/A9-2.png
    - assets/A9-3.png
    - assets/A9-4.png
    - assets/A9-5.png
    - assets/A9-6.png
    - assets/A9-7.png
    - assets/A9-8.png
    - assets/A9-9.png
    - assets/A9-10.png
    - assets/A9-11.png
    - assets/A9-12.png
    - assets/A9-13.png
    - assets/A9-14.png
    - assets/A9-15.png
    - assets/A9-16.png
    - assets/a-91.png
    - assets/a-92.png
    - assets/a-93.png
    - assets/a-94.png
    - assets/a-95.png
    - assets/a-96.png
    - assets/a21.png
    - assets/a22.png
    - assets/a23.png
    - assets/a24.png
    - assets/a25.png
    - assets/a26.png
    - assets/a27.png
    - assets/a28.png
    - assets/a51.png
    - assets/a61.png
    - assets/a62.png
    - assets/a63.png
    - assets/a64.png
    - assets/a65.png
    - assets/a66.png
    - assets/a71.png
    - assets/a72.png
    - assets/a73.png
    - assets/a74.png
    - assets/a75.png
    - assets/a76.png
    - assets/a77.png
    - assets/a751.png
    - assets/a752.png
    - assets/a753.png
    - assets/a754.png
    - assets/a755.png
    - assets/a756.png
    - assets/A-1-01.png
    - assets/A-2-01.png
    - assets/A-3-01.png
    - assets/A-4-01.png
    - assets/A-5-01.png
    - assets/A7sus2-1.png
    - assets/A7sus2-2.png
    - assets/A7sus2-3.png
    - assets/A7sus2-4.png
    - assets/A7sus2-5.png
    - assets/A7sus2-6.png
    - assets/A7sus4-1.png
    - assets/A7sus4-2.png
    - assets/A7sus4-3.png
    - assets/A7sus4-4.png
    - assets/A7sus4-5.png
    - assets/A7sus4-6.png
    - assets/A7sus4-7.png
    - assets/A7sus4-8.png
    - assets/A7sus4-9.png
    - assets/A-6-01.png
    - assets/Aadd9-1.png
    - assets/Aadd9-2.png
    - assets/Aadd9-3.png
    - assets/Aadd9-4.png
    - assets/Aadd9-5.png
    - assets/Aadd9-6.png
    - assets/Aadd9-7.png
    - assets/Aadd9-8.png
    - assets/Aaug-1.png
    - assets/Aaug-2.png
    - assets/Aaug-3.png
    - assets/Aaug-4.png
    - assets/Aaug-5.png
    - assets/Adim-1.png
    - assets/Adim-2.png
    - assets/Adim7-1.png
    - assets/Adim7-2.png
    - assets/Adim7-3.png
    - assets/Adim7-4.png
    - assets/Am-1.png
    - assets/Am-2.png
    - assets/Am-3.png
    - assets/Am-4.png
    - assets/Am-5.png
    - assets/Am-6.png
    - assets/Am6-1.png
    - assets/Am6-2.png
    - assets/Am6-3.png
    - assets/Am6-4.png
    - assets/Am6-5.png
    - assets/Am6-6.png
    - assets/Am6-7.png
    - assets/Am6-8.png
    - assets/Am7-1.png
    - assets/Am7-2.png
    - assets/Am7-3.png
    - assets/Am7-4.png
    - assets/Am7-5.png
    - assets/Am7-7.png
    - assets/Am7-8.png
    - assets/Am7-9.png
    - assets/Am7-10.png
    - assets/Am7-11.png
    - assets/Am7-12.png
    - assets/Am9-1.png
    - assets/Am9-2.png
    - assets/Am9-3.png
    - assets/Am9-4.png
    - assets/Am9-5.png
    - assets/Am9-6.png
    - assets/Am9-7.png
    - assets/Am-9-1.png
    - assets/Am-9-2.png
    - assets/Am-9-3.png
    - assets/Am-9-4.png
    - assets/Am-9-5.png
    - assets/Am-9-6.png
    - assets/Am-9-7.png
    - assets/Am-9-8.png
    - assets/Am-9-9.png
    - assets/Am-9-10.png
    - assets/Am-9-11.png
    - assets/Am-9-12.png
    - assets/Amaj7-1.png
    - assets/Amaj7-2.png
    - assets/Amaj7-3.png
    - assets/Amaj7-4.png
    - assets/Amaj7-5.png
    - assets/Amaj7-6.png
    - assets/Amaj7-7.png
    - assets/Amaj7-8.png
    - assets/Amaj7-9.png
    - assets/Amaj9-1.png
    - assets/Amaj9-2.png
    - assets/Amaj9-3.png
    - assets/Amaj9-4.png
    - assets/Amaj9-5.png
    - assets/Amaj9-6.png
    - assets/Amaj9-7.png
    - assets/Amaj9-8.png
    - assets/Amaj9-9.png
    - assets/Ammaj7-1.png
    - assets/Ammaj7-2.png
    - assets/Ammaj7-3.png
    - assets/Ammaj7-4.png
    - assets/Ammaj7-5.png
    - assets/Ammaj7-6.png
    - assets/Ammaj7-7.png
    - assets/Ammaj7-8.png
    - assets/Ammaj7-9.png
    - assets/Asus2-1.png
    - assets/Asus2-2.png
    - assets/Asus2-3.png
    - assets/Asus2-4.png
    - assets/Asus2-5.png
    - assets/Asus2-6.png
    - assets/Asus4-1.png
    - assets/Asus4-2.png
    - assets/Asus4-3.png
    - assets/Asus4-4.png
    - assets/Asus4-5.png
    - assets/Asus4-6.png
    - assets/Asus4-7.png
    - assets/A#2-1.png
    - assets/A#2-2.png
    - assets/A#2-3.png
    - assets/A#2-4.png
    - assets/A#2-5.png
    - assets/A#2-6.png
    - assets/A#2-7.png
    - assets/A#2-8.png
    - assets/A#5-1.png
    - assets/A#6-1.png
    - assets/A#6-2.png
    - assets/A#6-3.png
    - assets/A#6-4.png
    - assets/A#6-5.png
    - assets/A#6-6.png
    - assets/A#6-7.png
    - assets/A#7-1.png
    - assets/A#7-2.png
    - assets/A#7-3.png
    - assets/A#7-4.png
    - assets/A#7-5.png
    - assets/A#7-6.png
    - assets/A#7-7.png
    - assets/A#7-8.png
    - assets/A#7+5-1.png
    - assets/A#7+5-2.png
    - assets/A#7+5-3.png
    - assets/A#7+5-4.png
    - assets/A#7+5-5.png
    - assets/A#7+5-6.png
    - assets/A#7sus2-1.png
    - assets/A#7sus2-2.png
    - assets/A#7sus2-3.png
    - assets/A#7sus2-4.png
    - assets/A#7sus2-5.png
    - assets/A#7sus4-1.png
    - assets/A#7sus4-2.png
    - assets/A#7sus4-3.png
    - assets/A#7sus4-4.png
    - assets/A#7sus4-5.png
    - assets/A#7sus4-6.png
    - assets/A#7sus4-7.png
    - assets/A#7sus4-8.png
    - assets/A#7sus4-9.png
    - assets/A#9-1.png
    - assets/A#9-2.png
    - assets/A#9-3.png
    - assets/A#9-4.png
    - assets/A#9-5.png
    - assets/A#9-6.png
    - assets/A#9-7.png
    - assets/A#9-8.png
    - assets/A#9-9.png
    - assets/A#9-10.png
    - assets/A#9-11.png
    - assets/A#9-12.png
    - assets/A#9-13.png
    - assets/A#9-14.png
    - assets/A#9-15.png
    - assets/A#9-16.png
    - assets/A#9-17.png
    - assets/A#-9-1.png
    - assets/A#-9-2.png
    - assets/A#-9-3.png
    - assets/A#-9-4.png
    - assets/A#-9-5.png
    - assets/A#-9-6.png
    - assets/A#-9-7.png
    - assets/A#-9-8.png
    - assets/A#-9-9.png
    - assets/A#-1-01.png
    - assets/A#-2-01.png
    - assets/A#-3-01.png
    - assets/A#-4-01.png
    - assets/A#-5-01.png
    - assets/A#-6-01.png
    - assets/A#-7-01.png
    - assets/A#add9-1.png
    - assets/A#add9-2.png
    - assets/A#add9-3.png
    - assets/A#add9-4.png
    - assets/A#add9-5.png
    - assets/A#add9-6.png
    - assets/A#add9-7.png
    - assets/A#add9-8.png
    - assets/A#aug-1.png
    - assets/A#aug-2.png
    - assets/A#aug-3.png
    - assets/A#aug-4.png
    - assets/A#aug-5.png
    - assets/A#dim-1.png
    - assets/A#dim-2.png
    - assets/A#dim-3.png
    - assets/A#dim7-1.png
    - assets/A#dim7-2.png
    - assets/A#dim7-3.png
    - assets/A#dim7-4.png
    - assets/A#m-1.png
    - assets/A#m-2.png
    - assets/A#m-3.png
    - assets/A#m-4.png
    - assets/A#m-5.png
    - assets/A#m-6.png
    - assets/A#m6-1.png
    - assets/A#m6-2.png
    - assets/A#m6-3.png
    - assets/A#m6-4.png
    - assets/A#m6-5.png
    - assets/A#m6-6.png
    - assets/A#m6-7.png
    - assets/A#m6-8.png
    - assets/A#m7-1.png
    - assets/A#m7-2.png
    - assets/A#m7-3.png
    - assets/A#m7-4.png
    - assets/A#m7-5.png
    - assets/A#m7-6.png
    - assets/A#m7-7.png
    - assets/A#m7-8.png
    - assets/A#m7-9.png
    - assets/A#m7-10.png
    - assets/A#m7-11.png
    - assets/A#m9-1.png
    - assets/A#m9-2.png
    - assets/A#m9-3.png
    - assets/A#m9-4.png
    - assets/A#m9-5.png
    - assets/A#m9-6.png
    - assets/A#m-9-1.png
    - assets/A#m-9-2.png
    - assets/A#m-9-3.png
    - assets/A#m-9-4.png
    - assets/A#m-9-5.png
    - assets/A#m-9-6.png
    - assets/A#m-9-7.png
    - assets/A#m-9-8.png
    - assets/A#m-9-9.png
    - assets/A#m-9-10.png
    - assets/A#m-9-11.png
    - assets/A#maj7-1.png
    - assets/A#maj7-2.png
    - assets/A#maj7-3.png
    - assets/A#maj7-4.png
    - assets/A#maj7-5.png
    - assets/A#maj7-6.png
    - assets/A#maj7-7.png
    - assets/A#maj7-8.png
    - assets/A#mmaj7-1.png
    - assets/A#mmaj7-2.png
    - assets/A#mmaj7-2.png
    - assets/A#mmaj7-4.png
    - assets/A#mmaj7-5.png
    - assets/A#mmaj7-6.png
    - assets/A#mmaj7-7.png
    - assets/A#sus2-1.png
    - assets/A#sus2-2.png
    - assets/A#sus2-3.png
    - assets/A#sus2-4.png
    - assets/A#sus2-5.png
    - assets/A#sus4-1.png
    - assets/A#sus4-2.png
    - assets/A#sus4-3.png
    - assets/A#sus4-4.png
    - assets/A#sus4-5.png
    - assets/A#sus4-6.png
    - assets/A#sus4-7.png
    - assets/A#maj9-1.png
    - assets/A#maj9-2.png
    - assets/A#maj9-3.png
    - assets/A#maj9-4.png
    - assets/A#maj9-5.png
    - assets/A#maj9-6.png
    - assets/A#maj9-7.png
    - assets/A#maj9-8.png
    - assets/A#maj9-9.png
    - assets/A#maj9-10.png
    - assets/A#maj9-11.png
    - assets/B2-1.png
    - assets/B2-2.png
    - assets/B2-3.png
    - assets/B2-4.png
    - assets/B2-5.png
    - assets/B2-6.png
    - assets/B2-7.png
    - assets/B5-1.png
    - assets/B5-2.png
    - assets/B6-1.png
    - assets/B6-2.png
    - assets/B6-3.png
    - assets/B6-4.png
    - assets/B6-5.png
    - assets/B6-6.png
    - assets/B7-1.png
    - assets/B7-2.png
    - assets/B7-3.png
    - assets/B7-4.png
    - assets/B7-5.png
    - assets/B7-6.png
    - assets/B7-7.png
    - assets/B7-8.png
    - assets/B7+5-1.png
    - assets/B7+5-2.png
    - assets/B7+5-3.png
    - assets/B7+5-4.png
    - assets/B7+5-5.png
    - assets/B7+5-6.png
    - assets/B7sus2-1.png
    - assets/B7sus2-2.png
    - assets/B7sus2-3.png
    - assets/B7sus2-4.png
    - assets/B7sus2-5.png
    - assets/B7sus4-1.png
    - assets/B7sus4-2.png
    - assets/B7sus4-3.png
    - assets/B7sus4-4.png
    - assets/B7sus4-5.png
    - assets/B7sus4-6.png
    - assets/B7sus4-7.png
    - assets/B7sus4-8.png
    - assets/B7sus4-9.png
    - assets/B7sus4-10.png
    - assets/B9-1.png
    - assets/B9-2.png
    - assets/B9-3.png
    - assets/B9-4.png
    - assets/B9-5.png
    - assets/B9-6.png
    - assets/B9-7.png
    - assets/B9-8.png
    - assets/B9-9.png
    - assets/B9-10.png
    - assets/B9-11.png
    - assets/B9-12.png
    - assets/B9-13.png
    - assets/B9-14.png
    - assets/B9-15.png
    - assets/B-9-1.png
    - assets/B-9-2.png
    - assets/B-9-3.png
    - assets/B-9-4.png
    - assets/B-9-5.png
    - assets/Badd9-1.png
    - assets/Badd9-2.png
    - assets/Badd9-3.png
    - assets/Badd9-4.png
    - assets/Badd9-5.png
    - assets/Baug-1.png
    - assets/Baug-2.png
    - assets/Baug-3.png
    - assets/Baug-4.png
    - assets/B-1-01.png
    - assets/B-2-01.png
    - assets/B-3-01.png
    - assets/B-4-01.png
    - assets/B-5-01.png
    - assets/B-6-01.png
    - assets/Bdim-1.png
    - assets/Bdim-2.png
    - assets/Bdim7-1.png
    - assets/Bdim7-2.png
    - assets/Bdim7-3.png
    - assets/Bdim7-4.png
    - assets/Bm-1.png
    - assets/Bm-2.png
    - assets/Bm-3.png
    - assets/Bm-4.png
    - assets/Bm-5.png
    - assets/Bm-6.png
    - assets/Bm6-1.png
    - assets/Bm6-2.png
    - assets/Bm6-3.png
    - assets/Bm6-4.png
    - assets/Bm6-5.png
    - assets/Bm6-6.png
    - assets/Bm6-7.png
    - assets/Bm7-1.png
    - assets/Bm7-2.png
    - assets/Bm7-3.png
    - assets/Bm7-4.png
    - assets/Bm7-5.png
    - assets/Bm7-6.png
    - assets/Bm7-7.png
    - assets/Bm7-8.png
    - assets/Bm7-9.png
    - assets/Bm7-10.png
    - assets/Bm7-11.png
    - assets/Bm7-12.png
    - assets/Bm9-1.png
    - assets/Bm9-2.png
    - assets/Bm9-3.png
    - assets/Bm9-4.png
    - assets/Bm9-5.png
    - assets/Bm9-6.png
    - assets/Bm-9-1.png
    - assets/Bm-9-2.png
    - assets/Bm-9-3.png
    - assets/Bm-9-4.png
    - assets/Bm-9-5.png
    - assets/Bm-9-6.png
    - assets/Bm-9-7.png
    - assets/Bm-9-8.png
    - assets/Bm-9-9.png
    - assets/Bm-9-10.png
    - assets/Bm-9-11.png
    - assets/Bm-9-12.png
    - assets/Bmaj7-1.png
    - assets/Bmaj7-2.png
    - assets/Bmaj7-3.png
    - assets/Bmaj7-4.png
    - assets/Bmaj7-5.png
    - assets/Bmaj7-6.png
    - assets/Bmaj7-7.png
    - assets/Bmaj7-8.png
    - assets/Bmaj9-1.png
    - assets/Bmaj9-2.png
    - assets/Bmaj9-3.png
    - assets/Bmaj9-4.png
    - assets/Bmaj9-5.png
    - assets/Bmaj9-6.png
    - assets/Bmaj9-7.png
    - assets/Bmaj9-8.png
    - assets/Bmaj9-9.png
    - assets/Bmaj9-10.png
    - assets/Bmmaj7-1.png
    - assets/Bmmaj7-2.png
    - assets/Bmmaj7-3.png
    - assets/Bmmaj7-4.png
    - assets/Bmmaj7-5.png
    - assets/Bmmaj7-6.png
    - assets/Bmmaj7-7.png
    - assets/Bmmaj7-8.png
    - assets/Bsus2-1.png
    - assets/Bsus2-2.png
    - assets/Bsus2-3.png
    - assets/Bsus2-4.png
    - assets/Bsus2-5.png
    - assets/Bsus4-1.png
    - assets/Bsus4-2.png
    - assets/Bsus4-3.png
    - assets/Bsus4-4.png
    - assets/Bsus4-5.png
    - assets/Bsus4-6.png
    - assets/Bsus4-7.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    -  family: GreatVibes
       fonts:
         - asset: assets/GreatVibes-Regular.ttf
         - weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
