enum AuthStatus {
  NOT_DETERMINED,
  NOT_LOGGED_IN,
  LOGGED_IN,
  SIGNUP_SUCCESSFULLY,
  NOT_SIGNUP,
  EMAIL_EXIST,
  USERNAME_NO_AVAILABLE,
  USERNAME_AVAILABLE,
  USERNAME_SAVED,
  UNDEFINED_ERROR,
}